config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :announcements
      resources :articles
      resources :notifications

      root to: "users#index"
    end
  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  root 'welcome#index'

  resources :articles
  resources :announcements, only: [:index]
  resources :notifications, only: [:index]

  get '/terms', to: 'welcome#terms'
  get '/privacy', to: 'welcome#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Article.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Article.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = Article.all
    respond_to do |format|
      format.html
      format.json { render json: ArticleSerializer.new(@articles).serialized_json }
    end
  end

  def new
  end

  def create
    @article = Article.new(article_params)

    @article.save
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Articles List</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text</strong>
  <%= @article.text %>
</p>